# Generated by Django 6.0.6 on 2026-06-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipie_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
                ('image', models.ImageField(upload_to='recipie')),
            ],
        ),
    ]
